// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApoBg-Bv7_6x4kWP-nugdW97LbzERj7DI',
    appId: '1:797497356323:web:392c4485223330de208196',
    messagingSenderId: '797497356323',
    projectId: 'project1-be966',
    authDomain: 'project1-be966.firebaseapp.com',
    storageBucket: 'project1-be966.appspot.com',
    measurementId: 'G-TMV49H8FMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1sgV61sAeZYAaXGkPCWjMS2tg9gpxRo',
    appId: '1:797497356323:android:52419b8cd32437a2208196',
    messagingSenderId: '797497356323',
    projectId: 'project1-be966',
    storageBucket: 'project1-be966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMiDZzwkDjNnZv2rKgf_MaCh2ReF-QkwE',
    appId: '1:797497356323:ios:9695af1ade4cf4a7208196',
    messagingSenderId: '797497356323',
    projectId: 'project1-be966',
    storageBucket: 'project1-be966.appspot.com',
    iosClientId: '797497356323-6op6lehp59efo3et6p50mht9ctm0ledm.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeGameV25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMiDZzwkDjNnZv2rKgf_MaCh2ReF-QkwE',
    appId: '1:797497356323:ios:4eb045f7b3b26f9b208196',
    messagingSenderId: '797497356323',
    projectId: 'project1-be966',
    storageBucket: 'project1-be966.appspot.com',
    iosClientId: '797497356323-f9o7qbil5coqo9baj0i3681cvpmf4oog.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeGameV25.RunnerTests',
  );
}
